name: Publish Package to npm

on:
  workflow_call:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        
      - name: Setup Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: vite-plugin-version-manifest/package-lock.json
          registry-url: 'https://registry.npmjs.org'
          scope: '@jose.donas' # From your package.json


      - name: Install dependencies
        working-directory: ./vite-plugin-version-manifest
        run: npm ci

      - name: Build package
        working-directory: ./vite-plugin-version-manifest
        run: npm run build

      - name: Publish to npm
        working-directory: ./vite-plugin-version-manifest
        run: npm publish --no-git-checks
